In [105]:
import pandas as pd
import numpy as np
import re

1st Data Process for the housing price data.

In [106]:
df_train_price = pd.read_csv('/home/mw/input/hackathon255769/ruc_Class25Q2_train_price.csv')

/tmp/ipykernel_56/1231370925.py:1: DtypeWarning: Columns (3,32,34,43,46,49,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train_price = pd.read_csv('/home/mw/input/hackathon255769/ruc_Class25Q2_train_price.csv')

In [107]:
#查看数据情况
df_train_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103871 entries, 0 to 103870
Data columns (total 55 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   城市         103871 non-null  int64
 1   区域         103871 non-null  float64
 2   板块         103871 non-null  float64
 3   环线         40419 non-null   object
 4   Price      103871 non-null  float64
 5   房屋户型       103291 non-null  object
 6   所在楼层       103871 non-null  object
 7   建筑面积       103871 non-null  object
 8   套内面积       35984 non-null   object
 9   房屋朝向       103870 non-null  object
 10  建筑结构       103291 non-null  object
 11  装修情况       103291 non-null  object
 12  梯户比例       101252 non-null  object
 13  配备电梯       91520 non-null   object
 14  别墅类型       1443 non-null    object
 15  交易时间       103871 non-null  object
 16  交易权属       103871 non-null  object
 17  上次交易       78422 non-null   object
 18  房屋用途       103870 non-null  object
 19  房屋年限       59361 non-null   object
 20  产权所属       103871 non-null  object
 21  抵押信息       0 non-null       float64
 22  房屋优势       82635 non-null   object
 23  核心卖点       85257 non-null   object
 24  户型介绍       28771 non-null   object
 25  周边配套       60733 non-null   object
 26  交通出行       60607 non-null   object
 27  lon        103871 non-null  float64
 28  lat        103871 non-null  float64
 29  年份         103871 non-null  float64
 30  区县         96630 non-null   float64
 31  板块_comm    96293 non-null   float64
 32  环线位置       28097 non-null   object
 33  物业类别       75458 non-null   object
 34  建筑年代       68770 non-null   object
 35  开发商        67730 non-null   object
 36  房屋总数       96740 non-null   object
 37  楼栋总数       96740 non-null   object
 38  物业公司       65963 non-null   object
 39  绿 化 率      70988 non-null   object
 40  容 积 率      70717 non-null   float64
 41  物 业 费      72713 non-null   object
 42  建筑结构_comm  74752 non-null   object
 43  物业办公电话     34936 non-null   object
 44  产权描述       75458 non-null   object
 45  供水         73573 non-null   object
 46  供暖         30945 non-null   object
 47  供电         73579 non-null   object
 48  燃气费        71170 non-null   object
 49  供热费        31383 non-null   object
 50  停车位        69303 non-null   float64
 51  停车费用       68318 non-null   object
 52  coord_x    96740 non-null   float64
 53  coord_y    96740 non-null   float64
 54  客户反馈       103871 non-null  object
dtypes: float64(13), int64(1), object(41)
memory usage: 43.6+ MB

In [108]:
def fill_property_from_advantage(house_advantage, house_property):
    """
    从“房屋优势”列提取“满五年/满两年”，填补“房屋产权”的空缺
    :param house_advantage: 单条样本的“房屋优势”值（可能为NaN/字符串）
    :param house_property: 单条样本的“房屋产权”值（可能为NaN/字符串）
    :return: 处理后的“房屋产权”值
    """
    # 第一步：判断“房屋产权”是否为空（含NaN、空字符串、仅符号等无效值）
    # 清理“房屋产权”：去除前后空格和特殊符号（如“、”“，”）
    if pd.isna(house_property):
        clean_property = ""
    else:
        clean_property = str(house_property).strip().replace("、", "").replace(",", "")
    
    # 若“房屋产权”已有有效内容（非空），直接返回原值，不改动
    if clean_property != "":
        return house_property
    
    # 第二步：若“房屋产权”为空，从“房屋优势”中提取“满五年/满两年”
    # 先判断“房屋优势”是否为有效字符串
    if pd.isna(house_advantage):
        return house_property  # 优势为空，无法提取，保持产权空缺
    else:
        advantage_str = str(house_advantage)
    
    # 用正则精准匹配“满五年”或“满两年”（忽略前后无关字符，如“房本满五年”“、满两年”）
    match = re.search(r'满(五|两)年', advantage_str)
    if match:
        # 提取匹配结果（如“满五年”“满两年”）
        extracted_feature = match.group()
        return extracted_feature  # 用提取的特征填补产权
    else:
        return house_property  # 未匹配到，保持产权空缺

df_train_price["房屋年限"] = df_train_price.apply(
    lambda row: fill_property_from_advantage(row["房屋优势"], row["房屋年限"]),
    axis=1
)

In [109]:
#按列分块，提取series列
df_chengshi = df_train_price['城市']
df_quyu = df_train_price['区域']
df_bankuai = df_train_price['板块']
df_huanxian = df_train_price['环线']
df_Price = df_train_price['Price']
df_fangwuhuxing = df_train_price['房屋户型']
df_suozailouceng = df_train_price['所在楼层']
df_jianzhumianji = df_train_price['建筑面积']
df_taoneimianji = df_train_price['套内面积']
df_fangwuchaoxiang = df_train_price['房屋朝向']
df_jianzhujiegou = df_train_price['建筑结构']
df_zhuangxiuqingkuang = df_train_price['装修情况']
df_tihubili = df_train_price['梯户比例']
df_peibeidianti = df_train_price['配备电梯']
df_bieshuleixing = df_train_price['别墅类型']
df_jiaoyishijian = df_train_price['交易时间']
df_jiaoyiquanshu = df_train_price['交易权属']
df_shangcijiaoyi = df_train_price['上次交易']
df_fangwuyongtu = df_train_price['房屋用途']
df_fangwunianxian = df_train_price['房屋年限']
df_chanquansuoshu = df_train_price['产权所属']
df_diyaxinxi = df_train_price['抵押信息']
df_fangwuyoushi = df_train_price['房屋优势']
df_hexinmaidian = df_train_price['核心卖点']
df_huxingjieshao = df_train_price['户型介绍']
df_zhoubianpeitao = df_train_price['周边配套']
df_jiaotongchuxing = df_train_price['交通出行']
df_lon = df_train_price['lon']
df_lat = df_train_price['lat']
df_nianfen = df_train_price['年份']
df_quxian = df_train_price['区县']
df_bankuai_comm = df_train_price['板块_comm']
df_huanxianweizhi = df_train_price['环线位置']
df_wuyeleibie = df_train_price['物业类别']
df_jianzhuniandai = df_train_price['建筑年代']
df_kaifashang = df_train_price['开发商']
df_fangwuzongshu = df_train_price['房屋总数']
df_loudongzongshu = df_train_price['楼栋总数']
df_wuyegongsi = df_train_price['物业公司']
df_lvhualv = df_train_price['绿 化 率']
df_rongjilv = df_train_price['容 积 率']
df_wuyefei = df_train_price['物 业 费']
df_jianzhujiegou_comm = df_train_price['建筑结构_comm']
df_wuyebangongdianhua = df_train_price['物业办公电话']
df_chanquanmiaoshu = df_train_price['产权描述']
df_gongshui = df_train_price['供水']
df_gongnuan = df_train_price['供暖']
df_gongdian = df_train_price['供电']
df_ranqifei = df_train_price['燃气费']
df_gongrefei = df_train_price['供热费']
df_tingchewei = df_train_price['停车位']
df_tingchefeiyong = df_train_price['停车费用']
df_coord_x = df_train_price['coord_x']
df_coord_y = df_train_price['coord_y']
df_kehufankui = df_train_price['客户反馈']

In [110]:
#依次处理数据
huanxianweizhi_bank = []
for s in df_huanxian:
    if pd.isna(s):
        continue
    huanxianweizhi_bank.append(s)
    huanxianweizhi_bank = set(huanxianweizhi_bank)
    huanxianweizhi_bank = list(huanxianweizhi_bank)

ring_mapping = {
    "二环内": 0,
    "二至三环": 1,
    "三至四环": 2,
    "四至五环": 3,
    "五至六环": 4,
    "六环外": 5,
    
    "内环内": 6,
    "内环至中环": 7,
    "中环至外环": 8,
    "内环至外环": 9,
    "外环外": 10
}

df_huanxian = df_huanxian.map(ring_mapping)
df_huanxian = pd.DataFrame(df_huanxian)
df_huanxian

         环线
0       1.0
1       4.0
2       4.0
3       5.0
4       2.0
...     ...
103866  NaN
103867  NaN
103868  NaN
103869  NaN
103870  NaN

[103871 rows x 1 columns]

In [111]:
huxing_info = []
for s in df_fangwuhuxing:
    match_full = re.match(r"(\d+)室(\d+)厅(\d+)厨(\d+)卫", str(s))
    match_simple = re.match(r"(\d+)房间(\d+)卫", str(s))
    if match_full:
        shi = int(match_full.group(1))
        ting = int(match_full.group(2))
        chu = int(match_full.group(3))
        wei = int(match_full.group(4))
    elif match_simple:
        shi = int(match_simple.group(1))
        ting = 0
        chu = 0
        wei = int(match_simple.group(2))
    else:
        shi = np.nan
        ting = np.nan
        chu = np.nan
        wei = np.nan
    huxing_info.append([shi,ting,chu,wei])
df_fangwuhuxing = pd.DataFrame(huxing_info)
columns = ['室数','厅数','厨数','卫数']
df_fangwuhuxing.columns = columns
df_fangwuhuxing

         室数   厅数   厨数   卫数
0       2.0  1.0  1.0  1.0
1       3.0  1.0  1.0  1.0
2       3.0  2.0  1.0  2.0
3       6.0  3.0  1.0  3.0
4       1.0  0.0  0.0  1.0
...     ...  ...  ...  ...
103866  2.0  2.0  1.0  1.0
103867  3.0  1.0  1.0  1.0
103868  3.0  1.0  1.0  1.0
103869  3.0  1.0  1.0  1.0
103870  3.0  2.0  1.0  2.0

[103871 rows x 4 columns]

In [112]:
df_suozailouceng
louceng_info = []
for s in df_suozailouceng:
    match_outside = re.match(r'^(.*?)\s*\(', s) # 识别括号前的文字
    match_inside = re.search(r'共(\d+)层', s)
    if match_outside:
        floor_position = match_outside.group(1).strip()
    else:
        floor_position = None
    
    if match_inside:
        total_floors = int(match_inside.group(1))
    else:
        total_floors = None
    louceng_info.append([floor_position,total_floors])
df_suozailouceng = pd.DataFrame(louceng_info)
columns = ['楼层位置','总层数']
df_suozailouceng.columns = columns
df_suozailouceng['楼层位置'] = df_suozailouceng['楼层位置'].replace({'地下室':0,"底层":1,"低楼层": 2,'中楼层':3,'高楼层':4,'顶层':5}) 
df_suozailouceng

        楼层位置  总层数
0          3    5
1          5    6
2          2    6
3          1    2
4          3   10
...      ...  ...
103866     3    6
103867     2    9
103868     3    6
103869     3   17
103870     4   27

[103871 rows x 2 columns]

In [113]:
mianji = []
for s in df_jianzhumianji:
    match = re.search(r'(\d+\.?\d*)㎡', s)
    if match:
        area = float(match.group(1))
    else:
        area = None
    mianji.append([area])
df_jianzhumianji = pd.DataFrame(mianji)
columns = ['建筑面积']
df_jianzhumianji.columns = columns
df_jianzhumianji

          建筑面积
0        52.30
1       127.44
2       118.02
3       293.23
4        39.85
...        ...
103866   93.60
103867  132.00
103868   92.00
103869  123.00
103870  144.00

[103871 rows x 1 columns]

In [114]:
taoneimianji = []
for s in df_taoneimianji:
    if pd.isna(s): 
        taoneimianji.append([np.nan]) 
        continue
    match = re.search(r'(\d+\.?\d*)㎡', s)
    if match:
        area = float(match.group(1))
    else:
        area = np.nan
    taoneimianji.append([area])
df_taoneimianji = pd.DataFrame(taoneimianji)
columns = ['套内面积']
df_taoneimianji.columns = columns
df_taoneimianji

          套内面积
0          NaN
1       123.70
2       101.95
3       293.23
4        29.94
...        ...
103866     NaN
103867     NaN
103868     NaN
103869     NaN
103870     NaN

[103871 rows x 1 columns]

In [115]:
#提取房屋主要朝向
direction_map = {
    '东': ['东'],
    '南': ['南'],
    '西': ['西'],
    '北': ['北'],
    '东南': ['东', '南'],
    '西南': ['西', '南'],
    '东北': ['东', '北'],
    '西北': ['西', '北']
}

def get_base_directions(s):
    """将朝向字符串拆分为所有包含的基础方向（东/南/西/北）"""
    if pd.isna(s):
        return []
    # 按空格拆分原始朝向
    dir_elements = s.split(' ')
    # 提取基础方向
    base_dirs = []
    for elem in dir_elements:
        # 从映射表中获取基础方向
        base_dirs.extend(direction_map.get(elem, []))
    base_dirs_unique = list(set(base_dirs))
    order = ['东', '南', '西', '北']
    base_dirs_sorted = sorted(base_dirs_unique, key=lambda x: order.index(x))
    return ' '.join(base_dirs_sorted)

# 将基础朝向转换为主要朝向
def categorize_direction(standardized_dir):
    if pd.isna(standardized_dir):
        return None
    
    dir_list = standardized_dir
    has_south = '南' in dir_list
    has_north = '北' in dir_list
    has_east = '东' in dir_list
    has_west = '西' in dir_list
    
    # 南北通透（同时有南和北）
    if has_south and has_north:
        return 0
    # 纯南向（只有南）
    if has_south and not has_north and not has_east and not has_west:
        return 1
    # 纯北向（只有北）
    if has_north and not has_south and not has_east and not has_west:
        return 2
    # 东西向（有东和西，无南和北）
    if has_east and has_west and not has_south and not has_north:
        return 3
    # 南向为主（有南，无北）
    if has_south and not has_north:
        return 4
    # 北向为主（有北，无南）
    if has_north and not has_south:
        return 5
    # 其他组合
    return 6

df_fangwuchaoxiang = df_fangwuchaoxiang.apply(get_base_directions)
df_fangwuchaoxiang = df_fangwuchaoxiang.apply(categorize_direction)
df_fangwuchaoxiang = pd.DataFrame(df_fangwuchaoxiang)
columns = ['房屋朝向']
df_fangwuchaoxiang.columns = columns
df_fangwuchaoxiang

/tmp/ipykernel_56/4090730969.py:31: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if pd.isna(standardized_dir):

        房屋朝向
0          0
1          0
2          4
3          0
4          1
...      ...
103866     0
103867     1
103868     0
103869     0
103870     0

[103871 rows x 1 columns]

In [116]:
df_jianzhujiegou = df_jianzhujiegou.replace({'混合结构':0,'钢混结构':1,'砖混结构':2,'钢结构':3,'砖木结构':4,'框架结构':5,'未知结构':6})
df_jianzhujiegou = pd.DataFrame(df_jianzhujiegou)
df_jianzhujiegou

        建筑结构
0        0.0
1        0.0
2        1.0
3        0.0
4        1.0
...      ...
103866   1.0
103867   1.0
103868   2.0
103869   1.0
103870   1.0

[103871 rows x 1 columns]

In [117]:
def chinese_to_arabic(chinese):
    # 基础映射：数字与单位
    num_map = {
        '一': 1, '二': 2, '三': 3, '四': 4, '五': 5,
        '六': 6, '七': 7, '八': 8, '九': 9, '十': 10,
        '百': 100,'两':2, '零': 0
    }
    
    result = 0  # 最终结果
    current = 0  # 临时存储当前数字（用于组合单位）
    
    for char in chinese:
        num = num_map[char]
        if num in (10, 100, 1000):  # 遇到单位（十/百/千）
            # 若单位前无数字（如“十”“百”），默认单位前是1（如“十”=1×10）
            if current == 0:
                current = 1
            result += current * num  # 累加当前数字×单位（如“二十”=2×10）
            current = 0  # 重置临时值，准备处理下一段
        else:  # 遇到数字（一~九）
            current = num  # 暂存当前数字（如“二十四”中的“二”）
    
    # 处理末尾无单位的数字（如“二十四”中的“四”“一百三”中的“三”）
    result += current
    
    return result

In [118]:
tihubili = []
for s in df_tihubili:
    if pd.isna(s): 
        tihubili.append([np.nan,np.nan]) 
        continue
    match_tihu = re.match(r'(\w+)梯(\w+)户', s)
    elevator_chinese = match_tihu.group(1)
    house_chinese = match_tihu.group(2)
    elevator_num = chinese_to_arabic(elevator_chinese)
    house_num = chinese_to_arabic(house_chinese)
    tihubili.append([elevator_num,house_num])
df_tihubili = pd.DataFrame(tihubili)
columns = ['梯数','对应户数']
df_tihubili.columns = columns
df_tihubili

         梯数  对应户数
0       1.0   3.0
1       1.0   2.0
2       1.0   5.0
3       NaN   NaN
4       2.0  11.0
...     ...   ...
103866  1.0   2.0
103867  2.0   2.0
103868  1.0   2.0
103869  2.0   4.0
103870  2.0   3.0

[103871 rows x 2 columns]

In [119]:
df_peibeidianti = df_peibeidianti.replace({"有": 1, "无": 0})
df_peibeidianti = pd.DataFrame(df_peibeidianti)
df_peibeidianti.columns = ['配备电梯']
df_peibeidianti

        配备电梯
0        0.0
1        0.0
2        1.0
3        NaN
4        1.0
...      ...
103866   NaN
103867   1.0
103868   NaN
103869   1.0
103870   1.0

[103871 rows x 1 columns]

In [120]:
df_bieshuleixing = df_bieshuleixing.replace({None:0,'叠拼':1,'独栋':2,'联排':3,'双排':4,'双拼':5})
df_bieshuleixing = pd.DataFrame(df_bieshuleixing)
df_bieshuleixing

        别墅类型
0          0
1          0
2          0
3          2
4          0
...      ...
103866     0
103867     0
103868     0
103869     0
103870     0

[103871 rows x 1 columns]

In [121]:
# 交易年份保留年，月转化为季度
transaction_time = []
df_jiaoyishijian = pd.to_datetime(df_jiaoyishijian)
df_jiaoyinian = df_jiaoyishijian.dt.year
df_jiaoyiyue = df_jiaoyishijian.dt.month
jiaoyijidu = []
for s in df_jiaoyiyue:
    if (s >= 1) & (s <= 3):
        jiaoyijidu.append([0])
    elif (s >= 4) & (s <= 6):
        jiaoyijidu.append([1])
    elif (s >= 7) & (s <= 9):
        jiaoyijidu.append([2])
    elif (s >= 10) & (s <= 12):
        jiaoyijidu.append([3])
    else:
        jiaoyijidu.append([np.nan])
df_jiaoyijidu = pd.DataFrame(jiaoyijidu)
df_jiaoyishijian = pd.concat([df_jiaoyinian,df_jiaoyijidu],axis=1)
columns = ['交易年','交易季度']
df_jiaoyishijian.columns = columns
df_jiaoyishijian

         交易年  交易季度
0       2021     0
1       2020     3
2       2020     3
3       2023     0
4       2019     3
...      ...   ...
103866  2025     0
103867  2025     0
103868  2025     0
103869  2025     0
103870  2025     0

[103871 rows x 2 columns]

In [122]:
# 只保留年份
# df_shangcijiaoyi = pd.to_datetime(df_shangcijiaoyi) 该方法不能用，因为存在超过范围的时间

last_transaction = []
for s in df_shangcijiaoyi:
    if pd.isna(s):
        last_transaction.append([np.nan])
    else:
        s = str(s)
        parts = s.split('-')
        if int(parts[0]) > 2025:
            parts[0] = np.nan
            last_transaction.append([parts[0]])
        else:
            last_transaction.append([int(parts[0])])
df_shangcijiaoyi = pd.DataFrame(last_transaction)
columns = ['上次交易年']
df_shangcijiaoyi.columns = columns
df_shangcijiaoyi

         上次交易年
0       2013.0
1       2010.0
2       2013.0
3       2017.0
4       2017.0
...        ...
103866     NaN
103867     NaN
103868     NaN
103869     NaN
103870     NaN

[103871 rows x 1 columns]

In [123]:
fangwunianxian = []
for s in df_fangwunianxian:
    if s == '满五年':
        fangwunianxian.append([0])
    elif s == '满两年':
        fangwunianxian.append([1])
    elif s == '未满两年':
        fangwunianxian.append([2])
    else:
        fangwunianxian.append([np.nan])
df_fangwunianxian = pd.DataFrame(fangwunianxian)
columns = ['房屋年限']
df_fangwunianxian.columns = columns
df_fangwunianxian

        房屋年限
0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
...      ...
103866   NaN
103867   NaN
103868   NaN
103869   NaN
103870   NaN

[103871 rows x 1 columns]

In [124]:
df_chanquansuoshu = df_chanquansuoshu.replace({"非共有": 0, "共有": 1})
df_chanquansuoshu = pd.DataFrame(df_chanquansuoshu)
df_chanquansuoshu

        产权所属
0          0
1          0
2          0
3          0
4          0
...      ...
103866     0
103867     0
103868     0
103869     1
103870     0

[103871 rows x 1 columns]

In [125]:
jianzhuniandai = []
for s in df_jianzhuniandai:
    if pd.isna(s): 
        jianzhuniandai.append([np.nan,np.nan]) 
        continue
    try:
        parts = s.split('-')
        match_start = parts[0]
        match_end = re.match(r'(\d+)', parts[1])
        jianzhuniandai.append([int(match_start),int(match_end.group(0))])
    except:
        match_end = re.match(r'(\d+)', s)
        jianzhuniandai.append([int(match_end.group(0)),np.nan]) 
df_jianzhuniandai = pd.DataFrame(jianzhuniandai)
columns = ['起始年代','终止年代']
df_jianzhuniandai.columns = columns
df_jianzhuniandai

          起始年代    终止年代
0       1955.0  2000.0
1       2005.0     NaN
2       2011.0  2012.0
3       2009.0  2011.0
4       2003.0  2018.0
...        ...     ...
103866  2004.0  2016.0
103867  2008.0  2015.0
103868  1998.0  2000.0
103869  2008.0  2015.0
103870  2009.0  2021.0

[103871 rows x 2 columns]

In [126]:
hushu = []
for s in df_fangwuzongshu:
    if pd.isna(s): 
        hushu.append([np.nan]) 
        continue
    match = re.match(r'(\d+)', s)
    hushu.append([int(match.group(0))])
df_fangwuzongshu = pd.DataFrame(hushu)
columns = ['房屋总数']
df_fangwuzongshu.columns = columns
df_fangwuzongshu

          房屋总数
0       1317.0
1       2317.0
2       1554.0
3         66.0
4       1685.0
...        ...
103866  1745.0
103867  1285.0
103868   146.0
103869  1285.0
103870  2478.0

[103871 rows x 1 columns]

In [127]:
loudong = []
for s in df_loudongzongshu:
    if pd.isna(s): 
        loudong.append([np.nan]) 
        continue
    match = re.match(r'(\d+)', s)
    loudong.append([int(match.group(0))])
df_loudongzongshu = pd.DataFrame(loudong)
columns = ['楼栋总数']
df_loudongzongshu.columns = columns
df_loudongzongshu

        楼栋总数
0       19.0
1       40.0
2       20.0
3       27.0
4       19.0
...      ...
103866  29.0
103867  12.0
103868   6.0
103869  12.0
103870  27.0

[103871 rows x 1 columns]

In [128]:
lvhua = []
for s in df_lvhualv:
    if pd.isna(s): 
        lvhua.append([np.nan]) 
        continue
    match = re.match(r'(\d+\.?\d*|\.\d+)', s)
    match_float = float(match.group(0))
    lvhua.append([match_float*0.01])
df_lvhualv = pd.DataFrame(lvhua)
columns = ['绿化率']
df_lvhualv.columns = columns
df_lvhualv

          绿化率
0       0.300
1       0.300
2       0.300
3       0.401
4       0.600
...       ...
103866  0.300
103867  0.300
103868  0.250
103869  0.300
103870  0.550

[103871 rows x 1 columns]

In [129]:
wuyefei = []
for s in df_wuyefei:
    if pd.isna(s): 
        wuyefei.append([np.nan,np.nan]) 
        continue
    try:
        parts = s.split('-')
        match_start = float(parts[0])
        match_end = float((re.search(r'(\d+\.?\d*|\.\d+)', parts[1])).group(1))
        wuyefei.append([match_start,match_end])
    except:
        match_end = re.search(r'(\d+\.?\d*|\.\d+)', s)
        wuyefei.append([float(match_end.group(0)),float(match_end.group(0))]) 
df_wuyefei = pd.DataFrame(wuyefei)
columns = ['物业费下限','物业费上限']
df_wuyefei.columns = columns
df_wuyefei

        物业费下限  物业费上限
0        1.30   1.65
1        0.65   0.65
2        1.98   2.98
3        3.00   6.07
4        4.80   5.50
...       ...    ...
103866   0.50   0.50
103867   1.50   1.78
103868   0.35   0.35
103869   1.50   1.78
103870   0.80   1.60

[103871 rows x 2 columns]

In [130]:
#将商水和民水分开记录
def water_type_convert(water):
    if pd.isna(water):
        return [np.nan, np.nan]  # 空值两列均为0
    water = str(water).strip()  # 去除可能的空格
    has_commercial = "商水" in water  # 是否包含商水
    has_residential = "民水" in water  # 是否包含民水
    return [1 if has_commercial else 0, 1 if has_residential else 0]
df_gongshui = df_gongshui.apply(water_type_convert).apply(pd.Series)
df_gongshui.columns = ["商水", "民水"]  # 设置列名
df_gongshui

         商水   民水
0       0.0  1.0
1       1.0  1.0
2       1.0  1.0
3       0.0  1.0
4       1.0  1.0
...     ...  ...
103866  0.0  1.0
103867  0.0  1.0
103868  0.0  1.0
103869  0.0  1.0
103870  0.0  1.0

[103871 rows x 2 columns]

In [131]:
def heating_type_convert(heating):
    if pd.isna(heating):
        return [np.nan, np.nan, np.nan]  # 空值三列均为0
    heating = str(heating).strip()  # 去除空格，兼容“集中供暖 / 自采暖”等格式
    # 判断是否包含对应供暖方式
    has_central = "集中供暖" in heating
    has_self = "自采暖" in heating
    has_none = "无供暖" in heating
    return [
        1 if has_central else 0,
        1 if has_self else 0,
        1 if has_none else 0
    ]

# 应用函数生成三列矩阵
df_gongnuan = df_gongnuan.apply(heating_type_convert).apply(pd.Series)
df_gongnuan.columns = ["集中供暖", "自采暖", "无供暖"]  # 设置列名
df_gongnuan

        集中供暖  自采暖  无供暖
0        1.0  0.0  0.0
1        0.0  1.0  0.0
2        1.0  1.0  0.0
3        0.0  1.0  0.0
4        1.0  1.0  0.0
...      ...  ...  ...
103866   1.0  1.0  0.0
103867   0.0  1.0  0.0
103868   1.0  0.0  0.0
103869   0.0  1.0  0.0
103870   1.0  0.0  0.0

[103871 rows x 3 columns]

In [132]:
#将商电民电分开记录
def electricity_type_convert(electricity):
    if pd.isna(electricity):
        return [np.nan, np.nan]  # 空值两列均为0
    electricity = str(electricity).strip()  # 去除可能的空格
    has_commercial = "商电" in electricity  # 是否包含商电
    has_residential = "民电" in electricity  # 是否包含民电
    return [1 if has_commercial else 0, 1 if has_residential else 0]
df_gongdian = df_gongdian.apply(electricity_type_convert).apply(pd.Series)
df_gongdian.columns = ["商电", "民电"]  # 设置列名
df_gongdian

         商电   民电
0       0.0  1.0
1       1.0  1.0
2       1.0  1.0
3       0.0  1.0
4       1.0  1.0
...     ...  ...
103866  0.0  1.0
103867  0.0  1.0
103868  0.0  1.0
103869  0.0  1.0
103870  1.0  1.0

[103871 rows x 2 columns]

In [133]:
ranqifei = []
for s in df_ranqifei:
    if pd.isna(s): 
        ranqifei.append([np.nan,np.nan]) 
        continue
    try:
        parts = s.split('-')
        match_start = float(parts[0])
        match_end = float((re.search(r'(\d+\.?\d*|\.\d+)', parts[1])).group(1))
        ranqifei.append([match_start,match_end])
    except:
        match_end = re.search(r'(\d+\.?\d*|\.\d+)', s)
        ranqifei.append([float(match_end.group(0)),float(match_end.group(0))]) 
df_ranqifei = pd.DataFrame(ranqifei)
columns = ['燃气费下限','燃气费上限']
df_ranqifei.columns = columns
df_ranqifei

        燃气费下限  燃气费上限
0        2.61   2.61
1        2.61   2.61
2        2.61   2.61
3        2.61   2.63
4        2.61   2.63
...       ...    ...
103866   2.68   2.68
103867   2.68   2.68
103868   2.68   2.68
103869   2.68   2.68
103870   2.00   2.40

[103871 rows x 2 columns]

In [134]:
gongrefei = []
for s in df_gongrefei:
    if pd.isna(s): 
        gongrefei.append([np.nan,np.nan]) 
        continue
    try:
        parts = s.split('-')
        match_start = float(parts[0])
        match_end = float((re.search(r'(\d+\.?\d*|\.\d+)', parts[1])).group(1))
        gongrefei.append([match_start,match_end])
    except:
        match_end = re.search(r'(\d+\.?\d*|\.\d+)', s)
        gongrefei.append([float(match_end.group(0)),float(match_end.group(0))]) 
df_gongrefei = pd.DataFrame(gongrefei)
columns = ['供热费下限','供热费上限']
df_gongrefei.columns = columns
df_gongrefei

        供热费下限  供热费上限
0        30.0   30.0
1         NaN    NaN
2        30.0   30.0
3         NaN    NaN
4        30.0   45.0
...       ...    ...
103866   18.0   18.0
103867    NaN    NaN
103868   18.0   18.0
103869    NaN    NaN
103870   19.0   20.0

[103871 rows x 2 columns]

In [135]:
def parse_parking_fee(fee_str):
    # 处理空值
    if pd.isna(fee_str):
        return np.nan
    
    cleaned = str(fee_str).strip().lower()
    if "免费" in cleaned:
        return 0.0
    
    num_match = re.search(r'(\d+\.?\d*)', cleaned)
    if not num_match:
        return np.nan  # 无数字→空值
    fee_num = float(num_match.group(1))  # 转换为数字
    
    # 根据数字范围判断周期并换算为月费
    # 规则：0.5~10 → 小时费；10~100 → 天费；其他→保留原值
    if 0.5 <= fee_num < 10:
        # 小时费换算月费
        monthly_fee = fee_num * 24 * 30
        return round(monthly_fee, 2)  # 保留2位小数
    elif 10 <= fee_num <= 80:
        # 天费换算月费
        monthly_fee = fee_num * 30
        return round(monthly_fee, 2)
    else:
        # 保留原值
        return round(fee_num, 2)
    
parking_fee = df_tingchefeiyong.apply(parse_parking_fee)
df_tingchefeiyong = pd.DataFrame(parking_fee)
df_tingchefeiyong.columns = ['停车费用']
df_tingchefeiyong

          停车费用
0          NaN
1        150.0
2        150.0
3          NaN
4       1200.0
...        ...
103866     NaN
103867   300.0
103868     NaN
103869   300.0
103870     NaN

[103871 rows x 1 columns]

In [136]:
df_zhuangxiuqingkuang = df_zhuangxiuqingkuang.map({'毛坯':0,'简装':1,'精装':2,'其他':3})
df_zhuangxiuqingkuang = pd.DataFrame(df_zhuangxiuqingkuang)
df_zhuangxiuqingkuang

        装修情况
0        2.0
1        2.0
2        1.0
3        2.0
4        2.0
...      ...
103866   3.0
103867   0.0
103868   1.0
103869   2.0
103870   3.0

[103871 rows x 1 columns]

In [137]:
#查看交易权属有多少类别
jiaoyiquanshu_bank = []
for s in df_jiaoyiquanshu:
    if pd.isna(s):
        continue
    jiaoyiquanshu_bank.append(s)
    jiaoyiquanshu_bank = set(jiaoyiquanshu_bank)
    jiaoyiquanshu_bank = list(jiaoyiquanshu_bank)
print(jiaoyiquanshu_bank)

['央产房', '商品房', '已购公房', '一类经济适用房', '售后公房', '回迁房', '私产', '经济适用房', '定向安置房', '限价商品房', '二类经济适用房', '拆迁还建房', '房改房', '动迁安置房', '集资房']

In [138]:
#对类别进行再次归类
property_belonging = {
    # 保障性住房（政策限制，定向供应）
    "动迁安置房": 1,
    "拆迁还建房": 1,  # 与动迁安置房性质一致
    "回迁房": 1,  # 拆迁后回迁的保障性住房
    "定向安置房": 1,  # 定向供应给特定群体
    "经济适用房": 1,
    "一类经济适用房": 1,  # 经济适用房细分类型
    "二类经济适用房": 1,  # 经济适用房细分类型
    
    # 商品房（市场化，产权较完整）
    "商品房": 0,
    "限价商品房": 0,  # 虽有限价政策，但属市场化商品房范畴
    
    # 房改及政策性住房（源于福利分房，房改后私有化）
    "房改房": 2,  # 单位福利房通过房改出售给个人
    "已购公房": 2,  # 购买的公有住房（属房改范畴）
    "售后公房": 2,  # 公房出售给个人后形成的产权
    "央产房": 2,  # 中央单位的房改房，属政策性住房
    
    # 纯私有产权（无政策福利，完全私有）
    "私产": 3,  # 完全由个人拥有，无政策限制
    
    # 集资类住房（单位/集体集资，产权特殊）
    "集资房": 4  # 单位或集体集资建设，产权可能含共有成分
}

df_jiaoyiquanshu = df_jiaoyiquanshu.map(property_belonging)
df_jiaoyiquanshu = pd.DataFrame(df_jiaoyiquanshu)
df_jiaoyiquanshu

        交易权属
0          0
1          0
2          0
3          0
4          0
...      ...
103866     0
103867     0
103868     0
103869     0
103870     0

[103871 rows x 1 columns]

In [139]:
#查看房屋用途有多少类别
fangwuyongtu_bank = []
for s in df_fangwuyongtu:
    if pd.isna(s):
        continue
    fangwuyongtu_bank.append(s)
    fangwuyongtu_bank = set(fangwuyongtu_bank)
    fangwuyongtu_bank = list(fangwuyongtu_bank)
print(fangwuyongtu_bank)

['普通住宅', '写字楼', '商务公寓', '商业办公类', '四合院', '商务型公寓', '住宅式公寓', '酒店式公寓', '公寓/公寓', '车库', '公寓/住宅', '底商', '新式里弄', '公寓（住宅）', '公寓', '花园洋房', '商业', '商住两用', '老公寓', '别墅']

In [140]:
#对房屋用途进行再次归类
house_usage_bank = {
    # 普通住宅（纯居住，无特殊属性）
    "普通住宅": 0,
    
    # 住宅公寓（含“公寓”但以居住为主）
    "公寓/住宅": 1,
    "公寓/公寓": 1,  # 重复“公寓”，默认住宅属性
    "公寓（住宅）": 1,
    "老公寓": 1,
    "住宅式公寓": 1,
    "公寓": 1,  # 未明确属性的“公寓”默认归为住宅（更常见）
    
    # 特色住宅（独特形态/稀缺性）
    "四合院": 2,
    "花园洋房": 2,
    "新式里弄": 2,
    "别墅": 2,
    
    # 商业办公（纯商业/办公用途）
    "商务型公寓": 3,  # 偏向办公属性
    "写字楼": 3,
    "酒店式公寓": 3,  # 多为短期办公/经营用途
    "商业办公类": 3,
    "商务公寓": 3,
    "底商": 3,  # 底层商业，属商业经营
    "商业": 3,
    
    # 商住两用（混合属性）
    "商住两用": 4,
    
    # 其他（特殊用途）
    "车库": 5
}

df_fangwuyongtu = df_fangwuyongtu.map(house_usage_bank)
df_fangwuyongtu = pd.DataFrame(df_fangwuyongtu)
df_fangwuyongtu

        房屋用途
0        0.0
1        0.0
2        0.0
3        2.0
4        3.0
...      ...
103866   0.0
103867   0.0
103868   0.0
103869   0.0
103870   0.0

[103871 rows x 1 columns]

In [141]:
df_rongjilv = pd.DataFrame(df_rongjilv)
df_rongjilv.columns = ['容积率']

In [142]:
#对客户反馈列进行处理：主要逻辑如下
#首先，该列由逗号隔开分句，部分句子无意义，可以用逗号完成切分
#其次，将该列提及的内容抽样、借助大语言模型（豆包）总结关键词、正负面词并分类
#最后，检测每一句逗号隔开的分句有无关键词内容，若提及一次即在对应类别下计1分，并乘以正负面系数，每个主题下对应求和
#由于句子长短会对提及词语的次数造成影响，将计算出的得分除以匹配次数得到主题得分
# ---------------------- 1. 标准化词典
topic_keywords = {
    "设施硬件": ["光照","通风","网速","阳台","装修","照明灯","结构","厨房","储物","水","墙","窗户","空调","冷气","车库","厕所","浴室","楼体","灯光","排风口","水表","隔音","暖气","设备","房龄","房屋保养","楼板","配套","地砖","管道","采光","管线","地板","地面","家具","配置","天花板","热水","空气","地暖","网络","客厅","电","采暖","设施","外立面","信号","洗衣"],
    "空间布局": ["面积","布局","路况","地铁","楼间距","空间","风景","道路","房型","出行距离","位置","居住密度","地势","设计","景观","红绿灯","车位","停车","户型","人流量","街道","楼层","周边","视野","格局"],
    "环境体验": ["体验","素质","潮气","气味","交通","绿植","隔音","地段","绿化","通勤","公共区","卫生","银行","医院","生活圈","购物","社区商业","邻居","打车","垃圾","车流","邻里","建筑风格","社区秩序","园区","蚊虫","餐饮","商业配套","楼道","虫害","虫鼠","马路","小区","走廊"],
    "服务配套": ["服务","成熟度","安保","保安","维修","安防","管理","监控","智能","社区活动","条款","证件","价格","签约手续","合同","房东","看房","门禁","燃气费","信息","电费","保洁","物业","流程","治安","入住","停车费"]
}

positive_words = {"快","通透","稳定","时尚","预留","标准","顺畅","完善","新颖","舒适","充足","充裕","贴心","稳固","齐全","密封好","干爽","优","新","紧实","结实","考究","先进","用心","均衡","齐备","大","柔和","快捷","接入","流通","无遮挡","宽敞","实用","层高","规范","明确","合理","均匀","靠近","常见","良好","方正","优越","平坦","佳","开阔","临近","统一","平整","规整","紧凑","清新","新鲜","整洁","绿化好","率高","定期","排气","和谐","优美","现代","清理","干净","安静","清洁","友好","漂亮","丰富","高","接受","按时","好","清晰","节奏","方便","及时","沟通","严格","成熟","到位","安全","计量","保障","覆盖","便利","活动","强","独立","拎包","高效","正常","正规","常规","适中","普通","平均","中等","可接受","中档","一般"}

negative_words = {"老旧","松动","进风","漏水","渗水","裂","停用","坏","破损","异响","漏电","漏风","堵塞","不足","薄","不稳","不热","故障","不严","老化","低","遮挡","慢","暗","湿","远","离地铁","不便","拥挤","偏","刺鼻","噪音","堪忧","嘈杂","发黑","差","问题","闷","少","积灰","荒废","死角","难","返味","反味","杂乱","吵闹","堆放","多","纠纷","异味","油烟","发霉","脏乱","高","霸王","慢","隐患","拖延","推诿","违章","失效","陷阱","勉强","不清楚","偷工减料",'不畅'}

# ---------------------- 2. 核心处理函数（新增匹配次数+平均得分）
def calculate_topic_score_and_count(comment):
    """
    计算单条评论的4主题：得分、成功匹配次数、平均得分
    comment: 输入评论
    return: 字典（含得分、匹配次数、平均得分）
    """
    # 初始化：主题得分（0）、成功匹配次数（0）
    topic_scores = {topic: 0.0 for topic in topic_keywords.keys()}
    topic_match_count = {topic: 0 for topic in topic_keywords.keys()}  # 新增：成功匹配次数
    
    try:
        # 步骤1：切分子块并过滤无效值
        sub_blocks = [block.strip() for block in comment.split("，") if block.strip()]
        if not sub_blocks:
            return {"得分": topic_scores, "匹配次数": topic_match_count, "平均得分": topic_scores}
        
        # 步骤2：遍历子块，计算得分+次数
        for block in sub_blocks:
            block_topic = None  # 子块匹配的主题
            block_score = 1.0   # 基础分
            
            # 2.1 匹配主题（仅首个命中主题）
            for topic, keywords in topic_keywords.items():
                if any(keyword in block for keyword in keywords):
                    block_topic = topic
                    break
            if not block_topic:
                continue  # 未匹配主题，跳过
            
            # 2.2 调整正负面系数
            has_pos = any(p in block for p in positive_words)
            has_neg = any(n in block for n in negative_words)
            if has_pos and not has_neg:
                block_score *= 1.5
            elif has_neg and not has_pos:
                block_score *= 0.5  # 若需负向扣分，改为 * -1
            
            # 2.3 累加得分 + 统计匹配次数（关键：只要匹配主题，次数+1）
            topic_scores[block_topic] += block_score
            topic_match_count[block_topic] += 1  # 新增：成功匹配次数+1
        
        # 步骤3：计算平均得分（得分÷次数，次数为0时计0，避免除以0）
        topic_avg_score = {}
        for topic in topic_keywords.keys():
            count = topic_match_count[topic]
            topic_avg_score[topic] = round(topic_scores[topic] / count, 2) if count > 0 else 0.0
        
        return {
            "得分": {k: round(v, 2) for k, v in topic_scores.items()},
            "匹配次数": topic_match_count,
            "平均得分": topic_avg_score  # 衍生指标：消除“说得多”的影响
        }
    
    except Exception as e:
        # 报错时，所有指标计0
        print(f"处理评论「{comment}」出错：{str(e)}，所有指标计0")
        return {
            "得分": topic_scores,
            "匹配次数": topic_match_count,
            "平均得分": topic_scores
        }

In [143]:
df_kehufankui = pd.DataFrame(df_kehufankui)
df_kehufankui

                                客户反馈
0                       听说，设施老旧，停车费高
1                      整体印象，网速快，面积适中
2              地段一般，停车划线清晰，说白了，居住体验佳
3           暖气好，平均水准，厨房设备新，不过话说，气味中性
4           可以说，通风一般，空气清新，换个角度看，气味刺鼻
...                              ...
103866        说句实话，家具完好，严格意义上讲，空气流通好
103867             窗户大小适中，某种意义上，陷阱条款
103868              空调噪音大，总体看，公共照明到位
103869  个人觉得，房屋保养好，总体上说，通勤时间中等，阳台通风佳
103870        另一方面，门禁严格，大体情况如此，通风死角多

[103871 rows x 1 columns]

In [144]:
df_kehufankui['主题分析结果'] = df_kehufankui["客户反馈"].apply(calculate_topic_score_and_count)
for topic in topic_keywords.keys():
    df_kehufankui[f"{topic}_得分"] = df_kehufankui["主题分析结果"].apply(lambda x: x["得分"][topic])
    df_kehufankui[f"{topic}_匹配次数"] = df_kehufankui["主题分析结果"].apply(lambda x: x["匹配次数"][topic])
    df_kehufankui[f"{topic}_平均得分"] = df_kehufankui["主题分析结果"].apply(lambda x: x["平均得分"][topic])
df_kehufankui = df_kehufankui.drop("主题分析结果", axis=1)
df_kehufankui_origin = df_kehufankui.copy()
df_kehufankui = df_kehufankui.drop(["客户反馈","设施硬件_得分","设施硬件_匹配次数","空间布局_得分","空间布局_匹配次数","环境体验_得分","环境体验_匹配次数","服务配套_得分","服务配套_匹配次数"], axis=1)
df_kehufankui

        设施硬件_平均得分  空间布局_平均得分  环境体验_平均得分  服务配套_平均得分
0             0.5        1.0        0.0        0.0
1             1.5        1.5        0.0        0.0
2             0.0        1.5        1.5        0.0
3             1.5        0.0        1.0        0.0
4             1.5        0.0        0.5        0.0
...           ...        ...        ...        ...
103866        1.5        0.0        0.0        0.0
103867        1.5        0.0        0.0        0.5
103868        1.0        0.0        0.0        0.0
103869        1.5        0.0        1.5        0.0
103870        0.5        0.0        0.0        1.5

[103871 rows x 4 columns]

In [145]:
#拼接完成摘取的数据
df_usful_information = pd.concat(
    [df_chengshi,df_quyu,df_bankuai,df_huanxian,df_Price,df_fangwuhuxing,df_suozailouceng,df_jianzhumianji,df_taoneimianji,
     df_fangwuchaoxiang,df_jianzhujiegou,df_zhuangxiuqingkuang,df_tihubili,df_peibeidianti,df_bieshuleixing,
     df_jiaoyishijian,df_jiaoyiquanshu,df_shangcijiaoyi,df_fangwuyongtu,df_fangwunianxian,df_chanquansuoshu,df_lon,df_lat,
     df_jianzhuniandai,df_fangwuzongshu,df_loudongzongshu,df_lvhualv,df_rongjilv,df_gongshui,df_gongnuan,df_gongdian,
     df_ranqifei,df_gongrefei,df_tingchewei,df_tingchefeiyong,df_coord_x,df_coord_y,df_kehufankui],axis=1
    )
df_usful_information

,城市,区域,板块,环线,Price,室数,厅数,厨数,卫数,楼层位置,...,供热费下限,供热费上限,停车位,停车费用,coord_x,coord_y,设施硬件_平均得分,空间布局_平均得分,环境体验_平均得分,服务配套_平均得分
0,0,109.0,150.0,1.0,6.194049e+06,2.0,1.0,1.0,1.0,3,...,30.0,30.0,300.0,NaN,117.424278,40.975752,0.5,1.0,0.0,0.0
1,0,65.0,299.0,4.0,4.354153e+06,3.0,1.0,1.0,1.0,5,...,NaN,NaN,1550.0,150.0,117.389228,41.091295,1.5,1.5,0.0,0.0
2,0,62.0,911.0,4.0,3.321992e+06,3.0,2.0,1.0,2.0,2,...,30.0,30.0,324.0,150.0,117.200934,40.747919,0.0,1.5,1.5,0.0
3,0,123.0,1102.0,5.0,7.895656e+06,6.0,3.0,1.0,3.0,1,...,NaN,NaN,500.0,NaN,117.767308,41.228803,1.5,0.0,1.0,0.0
4,0,81.0,295.0,2.0,1.902960e+06,1.0,0.0,0.0,1.0,3,...,30.0,45.0,1800.0,1200.0,117.334530,40.952530,1.5,0.0,0.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103866,11,84.0,716.0,NaN,7.903242e+05,2.0,2.0,1.0,1.0,3,...,18.0,18.0,420.0,NaN,117.062762,40.513568,1.5,0.0,0.0,0.0
103867,11,84.0,716.0,NaN,1.113952e+06,3.0,1.0,1.0,1.0,2,...,NaN,NaN,NaN,300.0,117.075303,40.500796,1.5,0.0,0.0,0.5
103868,11,84.0,716.0,NaN,7.432028e+05,3.0,1.0,1.0,1.0,3,...,18.0,18.0,NaN,NaN,117.029481,40.498825,1.0,0.0,0.0,0.0
103869,11,84.0,716.0,NaN,1.290376e+06,3.0,1.0,1.0,1.0,3,...,NaN,NaN,NaN,300.0,117.075373,40.500866,1.5,0.0,1.5,0.0
103870,11,101.0,873.0,NaN,1.236439e+06,3.0,2.0,1.0,2.0,4,...,19.0,20.0,1600.0,NaN,116.497564,39.914396,0.5,0.0,0.0,1.5

In [146]:
check_cols = ['Price','建筑面积','绿化率', '容积率','室数', '厅数', '厨数', '卫数','总层数','梯数', '对应户数', '房屋总数', '楼栋总数','停车位', '停车费用']

In [147]:
def drop_outlier_rows(df, check_cols):
    """
    根据IQR法检测异常值，删除包含异常值的行，并返回删除的样本数
    """
    # 复制原始数据，避免修改输入
    df_copy = df.copy()
    original_rows = len(df_copy)  # 原始样本数
    
    # 存储每行是否为异常行（初始全为False）
    is_outlier = pd.Series([False] * original_rows, index=df_copy.index)
    
    # 对每个待筛查列计算IQR边界并标记异常行
    for col in check_cols:
        if col not in df_copy.columns:
            print(f"警告：列'{col}'不在DataFrame中，跳过该列")
            continue
        
        # 提取非NaN值计算IQR（排除缺失值，避免影响分位数）
        valid_vals = df_copy[col].dropna()
        
        # 计算IQR边界
        q1 = valid_vals.quantile(0.25)
        q3 = valid_vals.quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        # 标记该列中的异常值所在行（非NaN且超出边界）
        col_outlier = (df_copy[col] < lower_bound) | (df_copy[col] > upper_bound)
        # 排除NaN值（NaN不视为异常值，仅处理有值的异常）
        col_outlier = col_outlier & df_copy[col].notna()
        # 更新全局异常行标记（只要有一列异常，就标记为True）
        is_outlier = is_outlier | col_outlier
        print(f"列'{col}'：异常值边界 [{lower_bound:.4f}, {upper_bound:.4f}]，检测到{col_outlier.sum()}个异常值")
    
    # 删除所有异常行
    df_cleaned = df_copy[~is_outlier].copy()
    dropped = original_rows - len(df_cleaned)
    print(f"\n总计删除异常值样本数：{dropped}（原始样本数：{original_rows}，剩余样本数：{len(df_cleaned)}）")
    return df_cleaned

In [148]:
df_usful_information = drop_outlier_rows(df_usful_information, check_cols)

列'Price'：异常值边界 [-1793407.3053, 5365255.6393]，检测到7823个异常值
列'建筑面积'：异常值边界 [-0.6900, 190.4300]，检测到4126个异常值
列'绿化率'：异常值边界 [0.2100, 0.4500]，检测到14158个异常值
列'容积率'：异常值边界 [-0.3000, 5.3000]，检测到3711个异常值
列'室数'：异常值边界 [0.5000, 4.5000]，检测到3363个异常值
列'厅数'：异常值边界 [-0.5000, 3.5000]，检测到143个异常值
列'厨数'：异常值边界 [1.0000, 1.0000]，检测到2739个异常值
列'卫数'：异常值边界 [-0.5000, 3.5000]，检测到1371个异常值
列'总层数'：异常值边界 [-24.5000, 59.5000]，检测到3个异常值
列'梯数'：异常值边界 [-0.5000, 3.5000]，检测到7322个异常值
列'对应户数'：异常值边界 [-5.5000, 14.5000]，检测到7883个异常值
列'房屋总数'：异常值边界 [-2058.5000, 5241.5000]，检测到5943个异常值
列'楼栋总数'：异常值边界 [-27.5000, 64.5000]，检测到9983个异常值
列'停车位'：异常值边界 [-1492.5000, 3319.5000]，检测到4054个异常值
列'停车费用'：异常值边界 [-175.0000, 825.0000]，检测到6150个异常值

总计删除异常值样本数：48927（原始样本数：103871，剩余样本数：54944）

In [149]:
df_usful_information.to_csv('/home/mw/project/train_data_unfilled.csv',index=False)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from fancyimpute import IterativeImputer
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.gridspec import GridSpec

In [ ]:
df_train_price = pd.read_csv('test_data_unfilled.csv')

In [ ]:
# 按城市横切
df_chengshi_0 = df_train_price[df_train_price['城市'] == 0]
df_chengshi_1 = df_train_price[df_train_price['城市'] == 1]
df_chengshi_2 = df_train_price[df_train_price['城市'] == 2]
df_chengshi_3 = df_train_price[df_train_price['城市'] == 3]
df_chengshi_4 = df_train_price[df_train_price['城市'] == 4]
df_chengshi_5 = df_train_price[df_train_price['城市'] == 5]
df_chengshi_6 = df_train_price[df_train_price['城市'] == 6]
df_chengshi_7 = df_train_price[df_train_price['城市'] == 7]
df_chengshi_8 = df_train_price[df_train_price['城市'] == 8]
df_chengshi_9 = df_train_price[df_train_price['城市'] == 9]
df_chengshi_10 = df_train_price[df_train_price['城市'] == 10]
df_chengshi_11 = df_train_price[df_train_price['城市'] == 11]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer  # 替换为KNN填补


def process_city(
    city_df, 
    original_cols, 
    impute_threshold=0.5,
    continuous_cols=[],    # 连续浮点型变量
    int_cols=[],           # 连续整型变量（非年份）
    time_cols=[],          # 年份整型变量
    percent_cols=[],       # 百分数变量（0-1范围）
    categorical_cols=[]    # 分类变量（众数填补）
):
    """
    改进版：数值型变量用KNN填补，约束在原始min-max范围，分类变量用众数填补
    
    参数说明：
    - 数值型变量（连续/整型/年份/百分数）：KNN填补，限制在原始有效数据的min-max范围内
    - 百分数变量额外限制在0-1
    - 分类变量：众数填补
    """
    # 基于原始数据计算缺失率，确定需填补的列
    df_original = city_df.copy()  # 保留原始数据
    missing_ratio = df_original.isnull().mean()  # 基于原始数据计算缺失率
    
    # ----------------------
    # 确定各类型需填补的列（仅处理缺失率<阈值的列）
    # ----------------------
    categorical_to_impute = [
        col for col in categorical_cols
        if missing_ratio[col] < impute_threshold
    ]
    float_to_impute = [
        col for col in continuous_cols
        if missing_ratio[col] < impute_threshold
        and pd.api.types.is_numeric_dtype(df_original[col])
    ]
    # 百分数列单独处理（属于特殊连续型）
    percent_to_impute = [
        col for col in percent_cols
        if missing_ratio[col] < impute_threshold
        and pd.api.types.is_numeric_dtype(df_original[col])
    ]
    int_to_impute = [
        col for col in int_cols
        if missing_ratio[col] < impute_threshold
        and pd.api.types.is_numeric_dtype(df_original[col])
    ]
    time_to_impute = [
        col for col in time_cols
        if missing_ratio[col] < impute_threshold
        and pd.api.types.is_numeric_dtype(df_original[col])
    ]
    
    # 所有需要用KNN填补的数值列
    numeric_to_impute = float_to_impute + percent_to_impute + int_to_impute + time_to_impute
    # 需要范围约束的列
    cols_to_constrain = numeric_to_impute

    # 初始化处理数据集
    df_filled = df_original.copy()
    
    # ----------------------
    # 1. 计算各数值列的原始min-max边界（替代分位数，取消缩尾）
    # ----------------------
    col_bounds = {}  # 存储(原始min, 原始max)
    for col in cols_to_constrain:
        # 提取原始有效数据（排除NaN、inf、-inf）
        valid_vals = df_original[col].replace([np.inf, -np.inf], np.nan).dropna()
        if len(valid_vals) == 0:
            # 无有效数据时的默认边界
            if col in percent_to_impute:
                col_bounds[col] = (0.0, 1.0)  # 百分数默认0-1
            else:
                col_bounds[col] = (0.0, 0.0)  # 其他数值列默认0-0
        else:
            col_bounds[col] = (valid_vals.min(), valid_vals.max())


    # ----------------------
    # 3. 分类变量：众数填补
    # ----------------------
    if categorical_to_impute:
        for col in categorical_to_impute:
            mode_val = df_filled[col].mode()[0] if not df_filled[col].mode().empty else None
            df_filled[col] = df_filled[col].fillna(mode_val)
            # 处理分类变量中的inf（若为数值型）
            if pd.api.types.is_numeric_dtype(df_filled[col]):
                df_filled[col] = df_filled[col].replace([np.inf, -np.inf], mode_val)

    # ----------------------
    # 4. 数值型变量：KNN填补
    # ----------------------
    if numeric_to_impute:
        # KNN填补（n_neighbors=5可根据数据调整，weights='distance'加权平均）
        imputer = KNNImputer(n_neighbors=5, weights='distance')
        # 提取需填补的数值列
        impute_vals = df_filled[numeric_to_impute].values
        imputed_vals = imputer.fit_transform(impute_vals)  # KNN填补
        imputed_df = pd.DataFrame(imputed_vals, columns=numeric_to_impute, index=df_filled.index)
        
        # ----------------------
        # 5. 按变量类型约束范围（核心调整：用原始min-max替代分位数）
        # ----------------------
        # 连续浮点型：限制在原始min-max
        for col in float_to_impute:
            if col in imputed_df.columns and col in col_bounds:
                lower, upper = col_bounds[col]
                imputed_df[col] = imputed_df[col].clip(lower=lower, upper=upper)
        
        # 百分数：限制在原始min-max 且 0-1（双重约束）
        for col in percent_to_impute:
            if col in imputed_df.columns and col in col_bounds:
                lower, upper = col_bounds[col]
                # 先按原始范围约束，再强制0-1
                imputed_df[col] = imputed_df[col].clip(lower=lower, upper=upper).clip(0, 1)
        
        # 连续整型：限制在原始min-max后转整数
        for col in int_to_impute:
            if col in imputed_df.columns and col in col_bounds:
                lower, upper = col_bounds[col]
                imputed_df[col] = imputed_df[col].clip(lower=lower, upper=upper).round().astype(int)
        
        # 年份：限制在原始min-max后转整数
        for col in time_to_impute:
            if col in imputed_df.columns and col in col_bounds:
                lower, upper = col_bounds[col]
                imputed_df[col] = imputed_df[col].clip(lower=lower, upper=upper).round().astype(int)
        
        # 合并填补结果
        df_filled = df_filled.drop(numeric_to_impute, axis=1).join(imputed_df)

    # ----------------------
    # 6. 最终检查：确保约束生效
    # ----------------------
    for col in cols_to_constrain:
        if col in df_filled.columns and col in col_bounds:
            lower, upper = col_bounds[col]
            # 处理KNN可能产生的新异常值
            df_filled[col] = df_filled[col].replace(
                [np.inf, -np.inf], 
                [upper, lower]
            ).fillna(lower)
            # 确保类型正确
            if col in int_to_impute + time_to_impute:
                df_filled[col] = df_filled[col].round().astype(int)
            if col in percent_to_impute:
                df_filled[col] = df_filled[col].clip(0, 1)  # 再次确保百分数在0-1

    # 保持原始列顺序并返回
    result = df_filled.reindex(original_cols, axis=1)
    return result

def columns_preperation(df_0):
    df = df_0.copy()
    df['平均年代'] = (df['起始年代'] + df['终止年代'])/2
    df['平均燃气费'] = (df['燃气费下限'] + df['燃气费上限'])/2
    df['平均供热费'] = (df['供热费下限'] + df['供热费上限'])/2
    df['交易距今'] = 2025 - df['交易年']
    df['两次交易间隔'] = df['交易年'] - df['上次交易年']
    df['梯户比'] = df['梯数'] / df['对应户数']
    df = df.drop(['起始年代','终止年代','燃气费下限','燃气费上限','供热费下限','供热费上限','交易年','上次交易年','梯数','对应户数'],axis=1)
    return df

In [ ]:
def prepare(df_0,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1):
    df = df_0.copy()
    df =  process_city(df, df.columns.tolist(), 0.5,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols)
    df = columns_preperation(df)
    return df

In [ ]:
percent_cols=['绿化率']
categorical_cols=['城市','环线','楼层位置','房屋朝向', '建筑结构', '装修情况','配备电梯', '别墅类型','交易季度', '交易权属','房屋用途', '房屋年限', '产权所属',
                  '商水', '民水', '集中供暖', '自采暖', '无供暖', '商电', '民电']
continuous_cols=['建筑面积', '套内面积', 'lon', 'lat', '容积率','燃气费下限', '燃气费上限', '供热费下限', '供热费上限','停车费用','coord_x', 'coord_y',
                 '设施硬件_平均得分', '空间布局_平均得分', '环境体验_平均得分', '服务配套_平均得分']  
int_cols=['区域', '板块','室数', '厅数', '厨数', '卫数','总层数','梯数', '对应户数', '房屋总数', '楼栋总数','停车位']
time_cols=['交易年','上次交易年','起始年代', '终止年代']           
columns = ['室数','厅数','厨数','卫数','总层数','建筑面积','房屋总数','楼栋总数','绿化率','容积率','停车位','停车费用',
           '设施硬件_平均得分','空间布局_平均得分','环境体验_平均得分','服务配套_平均得分','梯户比','平均年代','平均燃气费','平均供热费','交易距今','两次交易间隔']


categorical_cols_1=['城市','环线','楼层位置','房屋朝向', '建筑结构', '装修情况','配备电梯', '别墅类型','交易季度', '交易权属','房屋用途', '房屋年限', '产权所属',
                  '商水', '民水', '集中供暖', '自采暖', '无供暖', '商电', '民电']
int_cols_1=['区域', '板块','室数', '厅数', '厨数', '卫数','总层数', '房屋总数', '楼栋总数','停车位']

In [ ]:
df_chengshi_0_fill = prepare(df_chengshi_0,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_1_fill = prepare(df_chengshi_1,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_2_fill = prepare(df_chengshi_2,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_3_fill = prepare(df_chengshi_3,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_4_fill = prepare(df_chengshi_4,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_5_fill = prepare(df_chengshi_5,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_6_fill = prepare(df_chengshi_6,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_7_fill = prepare(df_chengshi_7,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_8_fill = prepare(df_chengshi_8,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_9_fill = prepare(df_chengshi_9,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_10_fill = prepare(df_chengshi_10,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)
df_chengshi_11_fill = prepare(df_chengshi_11,columns,continuous_cols,int_cols,time_cols,percent_cols,categorical_cols,categorical_cols_1,int_cols_1)

In [ ]:
df_train_price_fill = pd.concat([df_chengshi_0_fill,df_chengshi_1_fill,df_chengshi_2_fill,df_chengshi_3_fill,df_chengshi_4_fill,
                            df_chengshi_5_fill,df_chengshi_6_fill,df_chengshi_7_fill,df_chengshi_8_fill,df_chengshi_9_fill,
                            df_chengshi_10_fill,df_chengshi_11_fill],axis=0)

In [ ]:
def fill_missing_by_type(df, cat_cols, cont_cols, binary_cols):
    """
    按变量类型填充缺失值：
    - 分类变量缺失值填充为999
    - 连续变量缺失值用非缺失值的中位数填充
    - 二值变量（0/1）缺失值用众数填充（0或1中出现次数更多的值）
    
    参数：
    df: DataFrame，待处理的数据集
    cat_cols: list，分类变量的列名列表（如['环线']）
    cont_cols: list，连续变量的列名列表（如['房屋年限', '停车费用']）
    binary_cols: list，二值变量（0/1）的列名列表（如['是否电梯房']）
    
    返回：
    DataFrame，填充缺失值后的数据集
    """
    # 校验：确保输入的列名都在数据集中
    all_cols = df.columns.tolist()
    for col in cat_cols + cont_cols + binary_cols:
        if col not in all_cols:
            raise ValueError(f"列名 '{col}' 不在数据集中，请检查输入的变量列表")
    
    # 校验：三类变量列表无重叠
    cat_set = set(cat_cols)
    cont_set = set(cont_cols)
    binary_set = set(binary_cols)
    
    overlap_cat_cont = cat_set & cont_set
    overlap_cat_binary = cat_set & binary_set
    overlap_cont_binary = cont_set & binary_set
    
    if overlap_cat_cont:
        raise ValueError(f"分类变量与连续变量存在重叠列：{overlap_cat_cont}，请修正")
    if overlap_cat_binary:
        raise ValueError(f"分类变量与二值变量存在重叠列：{overlap_cat_binary}，请修正")
    if overlap_cont_binary:
        raise ValueError(f"连续变量与二值变量存在重叠列：{overlap_cont_binary}，请修正")
    
    # 获取所有存在缺失值的列
    cols_with_missing = df.columns[df.isnull().any()].tolist()
    if not cols_with_missing:
        print("数据集中没有缺失值，无需处理")
        return df
    
    # 遍历有缺失值的列，按类型填充
    for col in cols_with_missing:
        # 1. 二值变量（0/1）：用众数填充（0或1中出现次数更多的值）
        if col in binary_cols:
            n_missing = df[col].isnull().sum()
            # 计算二值变量的众数（0或1）
            mode_val = df[col].mode()[0] if not df[col].mode().empty else 0  # 若众数为空（极端情况），默认填充0
            df.loc[df[col].isnull(), col] = mode_val
            print(f"二值变量 '{col}' 缺失值已用众数{mode_val}填充（缺失数量={n_missing}）")
        
        # 2. 分类变量：填充999（保持不变）
        elif col in cat_cols:
            df[col] = df[col].fillna(999)
            print(f"分类变量 '{col}' 缺失值已填充为999")
        
        # 3. 连续变量：用非缺失值的中位数填充
        elif col in cont_cols:
            non_missing_vals = df[col].dropna()
            # 计算非缺失值的中位数
            median_val = non_missing_vals.median()
            n_missing = df[col].isnull().sum()
            
            # 用中位数填充缺失值
            df.loc[df[col].isnull(), col] = median_val
            print(f"连续变量 '{col}' 缺失值已用中位数{median_val:.2f}填充（缺失数量={n_missing}）")
        
        # 4. 未纳入任何类型的列（提醒用户）
        else:
            print(f"警告：列 '{col}' 存在缺失值，但未被纳入分类/连续/二值变量列表，未处理")
    
    return df

In [ ]:
categorical_cols=['城市','环线','楼层位置','房屋朝向', '建筑结构', '装修情况','配备电梯', '别墅类型','交易季度', '交易权属','房屋用途', '房屋年限', '产权所属']
continuous_cols=['建筑面积', '套内面积', 'lon', 'lat', '容积率', '停车费用','coord_x', 'coord_y','设施硬件_平均得分','空间布局_平均得分','环境体验_平均得分','服务配套_平均得分'
                 ,'平均年代','平均燃气费','平均供热费','交易距今','两次交易间隔','梯户比','房屋总数','楼栋总数',
                 '绿化率','停车位']
binary_cols=['商水', '民水', '集中供暖', '自采暖', '无供暖', '商电', '民电']

In [ ]:
df_train_price_fill = fill_missing_by_type(df_train_price_fill,categorical_cols,continuous_cols,binary_cols)

In [ ]:
#依据城市缺失型添加
df_train_price_fill = df_train_price_fill.drop(['套内面积','板块'],axis=1)
df_train_price_fill['是否无环线'] = (df_train_price_fill['城市'].isin([1,2,3,5,6,7,8,9,10,11])).astype(int)
df_train_price_fill['是否无暖气'] = (~df_train_price_fill['城市'].isin([0,1,2,4,6,11])).astype(int)
df_train_price_fill['是否无房屋年限'] = (df_train_price_fill['城市'].isin([3,5,6,7,8,9,11])).astype(int)
df_train_price_fill['是否无绿化率_停车位_平均燃气费'] = (df_train_price_fill['城市'].isin([3,9])).astype(int)
df_train_price_fill['是否无停车费用'] = (df_train_price_fill['城市'].isin([3,6,9])).astype(int)
df_train_price_fill['是否无交易权属'] = (df_train_price_fill['城市'].isin([7,8])).astype(int)
df_train_price_fill['是否无房屋楼栋和社区位置'] = (df_train_price_fill['城市'].isin([9])).astype(int)
df_train_price_fill['是否无两次交易间隔'] = (df_train_price_fill['城市'].isin([5,6,8,9,11])).astype(int)
df_train_price_fill['是否无平均年代'] = (df_train_price_fill['城市'].isin([3,5,9])).astype(int)

In [ ]:

#转化平均年代至今
df_train_price_fill['平均年代'] = 2026-df_train_price_fill['平均年代']

In [ ]:
categorical_cols=['城市','区域','环线','楼层位置','房屋朝向', '建筑结构', '装修情况', '别墅类型','交易季度', '交易权属','房屋用途', '房屋年限']  # 需要转换的分类变量列

for col in categorical_cols:
    df_train_price_fill[col] = df_train_price_fill[col].astype('category')

# 2. 生成哑变量：对每个分类变量，生成k-1个哑变量
df_dummies = pd.get_dummies(
    df_train_price_fill, 
    columns=categorical_cols,  # 需要转换的分类变量列
    drop_first=True,  # 删除第一个类别（作为参照组）
    prefix=categorical_cols  # 哑变量前缀（方便区分）
)

In [ ]:
def apply_log_transform(df, cols_to_log):
    """
    对指定列进行自然对数转换（ln），处理非正值以避免错误
    
    :param df: 输入DataFrame（如df_dummies）
    :param cols_to_log: 需要取对数的列名列表（如['面积', '房价']）
    :param offset: 偏移量，用于处理非正值（如0或负数），默认+1（确保转换后的值>0）
    :return: 新增对数转换列的DataFrame（不修改原列）
    """
    # 复制数据，避免修改原始数据
    df_transformed = df.copy()
    
    # 2. 对每列进行对数转换
    for col in cols_to_log:
        # 提取原始列
        original = df_transformed[col]
        
        # 3. 计算自然对数（ln），新增列名：原列名 + "_log"
        log_col = f"{col}_log"
        df_transformed[log_col] = np.log(original+1)
        print(f"已对列'{col}'完成自然对数转换，新增列：{log_col}")
    
    return df_transformed

In [ ]:
cols_to_log = ['建筑面积','房屋总数','停车位','停车费用','楼栋总数','平均年代','容积率','平均供热费']
df_params = apply_log_transform(df_dummies,cols_to_log)

In [ ]:
# 生成交乘项
def generate_interactions(df, cols):
    """
    生成指定列中“第一项与其他项”的交乘项（仅第一项×第二项、第一项×第三项...）
    
    :param df: 原始DataFrame
    :param cols: 列名列表（第一项为基准因子，后续项为与基准因子相乘的列）
    :return: 包含原始列和新增交乘项的DataFrame
    """
    # 复制原始数据，避免修改输入
    df_new = df.copy()
    
    # 检查输入列是否为数值型（交乘项需数值型）
    non_numeric_cols = [col for col in cols if not pd.api.types.is_numeric_dtype(df_new[col])]
    if non_numeric_cols:
        raise TypeError(f"以下列不是数值型，无法生成交乘项：{non_numeric_cols}（请确保列是int/float类型）")
    
    # 提取基准因子（第一项）和需要与之相乘的列（第二项到最后一项）
    base_factor = cols[0]  # 第一个因子
    other_factors = cols[1:]  # 后续需要相乘的因子
    
    # 5. 生成交乘项
    for factor in other_factors:
        interaction_name = f"{base_factor}_{factor}"  # 交乘项命名：基准因子_其他因子
        df_new[interaction_name] = df_new[base_factor] * df_new[factor]
        print(f"已生成交乘项：{interaction_name}")
    
    return df_new

In [ ]:
df_params = generate_interactions(df_params,cols = ['是否无环线','环线_1.0', '环线_2.0', '环线_3.0', '环线_4.0', '环线_5.0', '环线_6.0', '环线_7.0', '环线_8.0', '环线_10.0','环线_999.0'])
df_params = generate_interactions(df_params,cols = ['是否无交易权属','交易权属_1.0', '交易权属_2.0', '交易权属_3.0', '交易权属_4.0'])
df_params = generate_interactions(df_params,cols = ['是否无房屋年限','房屋年限_1.0', '房屋年限_2.0','房屋年限_999.0'])
df_params = generate_interactions(df_params,cols = ['是否无房屋楼栋和社区位置','房屋总数_log', '楼栋总数_log'])
df_params = generate_interactions(df_params,cols = ['是否无绿化率_停车位_平均燃气费','绿化率', '容积率_log', '商水', '民水', '集中供暖', '自采暖', '商电', '民电', '停车位_log', '停车费用_log','平均燃气费'])
df_params = generate_interactions(df_params,cols = ['是否无停车费用', '停车费用_log'])
df_params = generate_interactions(df_params,cols = ['是否无暖气', '集中供暖', '自采暖', '平均供热费_log'])
df_params = generate_interactions(df_params,cols = ['是否无平均年代', '平均年代_log'])
df_params = generate_interactions(df_params,cols = ['是否无两次交易间隔', '两次交易间隔'])

In [ ]:
df_params = generate_interactions(df_params,cols = ['配备电梯', '梯户比'])
df_params = generate_interactions(df_params,cols = ['建筑面积_log','别墅类型_1', '别墅类型_2', '别墅类型_3', '别墅类型_5'])
df_params = generate_interactions(df_params,cols = ['配备电梯', '楼层位置_1', '楼层位置_2', '楼层位置_3', '楼层位置_4', '楼层位置_5','总层数','建筑面积_log'])

In [ ]:
# 去除X中对Y影响不明显的部分，以及去除对数化前原始变量列
df_params = df_params.drop(['coord_x', 'coord_y','建筑面积','房屋总数','停车位','停车费用','无供暖','平均年代','容积率','平均供热费','lon','lat'],axis=1)
df_X = df_params.copy()

In [ ]:
# 防止回归报错
for col in df_X.columns:
        # pd.to_numeric：将列转为数值型，errors='coerce'表示非数值转为NaN
        df_X[col] = pd.to_numeric(df_X[col])
        
        # 转换为float类型（确保即使原是int，也统一为float）
        df_X[col] = df_X[col].astype(float)

In [ ]:
# 对Price做对数化处理
df_Y = np.log(df_Price)
# 去除X中对Y影响不明显的部分，以及去除对数化前原始变量列
df_params = df_params.drop(['coord_x', 'coord_y','建筑面积','房屋总数','停车位','停车费用','无供暖','平均年代','容积率','平均供热费','lon','lat'],axis=1)
df_X = df_params.copy()

In [ ]:
#考虑到区域列样本和测试集有所不同，加入一列
df_X['others'] = False

In [ ]:
# 防止回归报错
for col in df_X.columns:
        # pd.to_numeric：将列转为数值型，errors='coerce'表示非数值转为NaN
        df_X[col] = pd.to_numeric(df_X[col])
        
        # 转换为float类型（确保即使原是int，也统一为float）
        df_X[col] = df_X[col].astype(float)

In [ ]:
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
df_X_with_const = sm.add_constant(df_X)  # 新增一列常数项
# 划分训练集和测试集
X_train, X_test, y_train, y_test = train_test_split(df_X_with_const, df_Y, test_size=0.2, random_state=42, shuffle=True)

In [ ]:
# 构建并拟合模型
model = sm.OLS(y_train, X_train).fit()
# OLS回归MAE
y_pred = model.predict(X_train)
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(np.exp(y_train), np.exp(y_pred))
print('训练集MAE: '+str(mae))
y_pred = model.predict(X_test)
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(np.exp(y_test), np.exp(y_pred))
print('测试集MAE: '+str(mae))

In [ ]:
#六折交叉验证
from sklearn.model_selection import KFold  # 用于分割交叉验证集
from sklearn.metrics import mean_absolute_error, r2_score  # 评估指标

kf = KFold(n_splits=6, shuffle=True, random_state=42)

# 存储每次验证的指标
cv_metrics = {
    'train_r2': [],    # 训练集R²
    'val_r2': [],      # 验证集R²
    'train_mae': [],   # 训练集MAE
    'val_mae': []      # 验证集MAE
}

for fold, (train_idx, val_idx) in enumerate(kf.split(df_X), 1):
    print(f"===== 第{fold}折 =====")
    
    # 分割训练集和验证集
    X_train, X_val = df_X.iloc[train_idx], df_X.iloc[val_idx]  # 自变量
    y_train, y_val = df_Y.iloc[train_idx], df_Y.iloc[val_idx]  # 因变量
    
    # 添加常数项（OLS必需）
    X_train_with_const = sm.add_constant(X_train)
    X_val_with_const = sm.add_constant(X_val)
    
    # 拟合OLS模型（用训练集）
    model = sm.OLS(y_train, X_train_with_const).fit()
    
    # 在训练集和验证集上预测
    y_train_pred = model.predict(X_train_with_const)
    y_val_pred = model.predict(X_val_with_const)
    
    # 计算评估指标
    train_r2 = r2_score(y_train, y_train_pred)
    val_r2 = r2_score(y_val, y_val_pred)
    train_mae = mean_absolute_error(np.exp(y_train), np.exp(y_train_pred))
    val_mae = mean_absolute_error(np.exp(y_val), np.exp(y_val_pred))
    
    # 存储指标
    cv_metrics['train_r2'].append(train_r2)
    cv_metrics['val_r2'].append(val_r2)
    cv_metrics['train_mae'].append(train_mae)
    cv_metrics['val_mae'].append(val_mae)
    
    # 打印当前折的结果
    print(f"训练集R²：{train_r2:.4f}，验证集R²：{val_r2:.4f}")
    print(f"训练集MAE：{train_mae:.4f}，验证集MAE：{val_mae:.4f}\n")

    cv_results = pd.DataFrame({
    '指标': ['平均训练R²', '平均验证R²', '训练R²标准差', '验证R²标准差',
            '平均训练MAE', '平均验证MAE', '训练MAE标准差', '验证MAE标准差'],
    '数值': [
        np.mean(cv_metrics['train_r2']),
        np.mean(cv_metrics['val_r2']),
        np.std(cv_metrics['train_r2']),
        np.std(cv_metrics['val_r2']),
        np.mean(cv_metrics['train_mae']),
        np.mean(cv_metrics['val_mae']),
        np.std(cv_metrics['train_mae']),
        np.std(cv_metrics['val_mae'])
    ]
})
print("===== 六折交叉验证结果汇总 =====")
print(cv_results.round(4))

In [ ]:
df_X = pd.read_csv('/home/mw/project/New Lasso/trian_price_X.csv')
df_Y = pd.read_csv('/home/mw/project/New Lasso/trian_price_Y.csv')

In [ ]:
from sklearn.preprocessing import StandardScaler  # 标准化必需
from sklearn.linear_model import Lasso, Ridge  # 回归模型
from sklearn.model_selection import GridSearchCV,cross_val_score, KFold
from sklearn.metrics import mean_absolute_error,r2_score
# 标准化自变量
scaler = StandardScaler()  # 基于训练数据的均值和标准差标准化
X_scaled = scaler.fit_transform(df_X)  # 转换为numpy数组
X_scaled = pd.DataFrame(X_scaled, columns=df_X.columns, index=df_X.index)  # 恢复为DataFrame

# 不调参模型（默认alpha=1.0）
lasso_default = Lasso(alpha=1.0, max_iter=10000, random_state=42)
ridge_default = Ridge(alpha=1.0, random_state=42)

# 调参模型（交叉验证选最优alpha）
lasso = Lasso(
    max_iter = 8000,
    random_state = 42
)
param_grid = {'alpha': np.logspace(-3, 3, 100)}  # 与之前的alphas一致
lasso_tuned = GridSearchCV(
    estimator=lasso,  # 基础模型
    param_grid=param_grid,  # 要搜索的参数
    cv=6,  # 6折交叉验证
    scoring='neg_mean_absolute_error',  # 用MAE评分
    n_jobs=-1  # 并行计算（加速
)

ridge = Ridge(
    max_iter=8000,  # 这里可以自定义迭代次数
    random_state=42
)
param_grid = {'alpha': np.logspace(-3, 3, 100)}  # 与之前的alphas一致
ridge_tuned = GridSearchCV(
    estimator=ridge,  # 基础模型
    param_grid=param_grid,  # 要搜索的参数
    cv=6,  # 6折交叉验证
    scoring='neg_mean_absolute_error',  # 用MAE评分
    n_jobs=-1  # 并行计算（加速）
)

In [ ]:

def evaluate(model, X, y, model_name):
    # 1. 训练模型（对GridSearchCV，fit会完成调参；对普通模型，fit是常规训练）
    model.fit(X, y)
    
    # 2. 训练集表现（统一计算）
    y_pred = model.predict(X)
    train_mae = mean_absolute_error(np.exp(y), np.exp(y_pred))
    train_r2 = r2_score(y, y_pred)
    
    # 3. 区分模型类型，获取交叉验证结果（核心优化：避免重复CV）
    if isinstance(model, GridSearchCV):
        # 3.1 对GridSearchCV调参模型：复用内部交叉验证结果
        # 最优参数对应的交叉验证MAE（取负，因scoring用neg_mean_absolute_error）
        cv_mae = -model.cv_results_['mean_test_score'][model.best_index_]
        # 交叉验证R²（需额外计算一次，但只针对最优模型，耗时少）
        kf = KFold(n_splits=model.cv, shuffle=True, random_state=42)  # 复用调参时的折数
        cv_r2 = cross_val_score(model.best_estimator_, X, y, cv=kf, scoring='r2').mean()
        # 获取最优alpha
        alpha = model.best_params_['alpha']
        
    else:
        # 3.2 对普通模型（如不调参的Lasso/Ridge）：需做交叉验证
        kf = KFold(n_splits=5, shuffle=True, random_state=42)
        cv_mae = -cross_val_score(
            model, X, y, cv=kf, scoring='neg_mean_absolute_error'
        ).mean()
        cv_r2 = cross_val_score(model, X, y, cv=kf, scoring='r2').mean()
        # 获取alpha（普通模型的alpha参数）
        alpha = model.alpha if hasattr(model, 'alpha') else None  # 容错处理
    
    return {
        '模型名称': model_name,
        'alpha值': round(alpha, 6) if alpha is not None else None,
        '训练集MAE': round(train_mae, 6),
        '训练集R²': round(train_r2, 6),
        '交叉验证MAE': round(cv_mae, 6),
        '交叉验证R²': round(cv_r2, 6)
    }

In [ ]:

results = [
    evaluate(lasso_default, X_scaled, df_Y, 'Lasso（不调参）'),
    evaluate(lasso_tuned, X_scaled, df_Y, 'Lasso（调参）'),
    evaluate(ridge_default, X_scaled, df_Y, '岭回归（不调参）'),
    evaluate(ridge_tuned, X_scaled, df_Y, '岭回归（调参）')
]
results_df = pd.DataFrame(results)
print(results_df)

In [ ]:
from joblib import dump

# 保存多个模型（同样用字典）
models = {
    "lasso_default": lasso_default,
    "lasso_tuned": lasso_tuned,
    "ridge_default": ridge_default,
    "ridge_tuned": ridge_tuned
}

# 保存（通常用.joblib后缀）
dump(models, "trained_models.joblib")